{ self, ... }:
{
  flake.nixosModules.domicileHardware =
    # This file was generated by `nixos-generate-config`
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
        self.nixosModules.acer
      ];

      boot.initrd.availableKernelModules = [
        "ahci"
        "xhci_pci"
        "usb_storage"
        "sd_mod"
        "sdhci_pci"
        "rtsx_pci_sdmmc"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-5a1e1392-6f42-41f1-b854-037e0f8bf2b3";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-5a1e1392-6f42-41f1-b854-037e0f8bf2b3".device =
        "/dev/disk/by-uuid/5a1e1392-6f42-41f1-b854-037e0f8bf2b3";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/133B-2D55";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [ ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
