[bar.default]
center = [ "workspaces" ]
contact_shadow = true
end = [ "notifications", "bluetooth", "network", "volume", "brightness", "battery", "clock" ]
margin_ends = 0
radius = 0
shadow = false
start = [ "clipboard", "taskbar", "media" ]

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 10

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "power_profile"

[desktop_widgets]
enabled = false

[hot_corners]
enabled = true

    [hot_corners.top_right]
    action = "launcher"

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.0
tint_intensity = 0.0
wallpaper = "/home/dominictdavies/MyNixOS/assets/wallpapers/stanley_parable_desk_lined.png"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-3", "lockscreen-login-box@DP-4", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1032.0
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-3"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-4"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 961.0
    output = "DP-4"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-4".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 961.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 720.0
    cy = 841.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 128.0
    box_width = 288.0
    cx = 1280.0
    cy = 368.0
    output = "DP-2"
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 312.0
    box_width = 360.0
    cx = 1284.0
    cy = 620.0
    output = "DP-2"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        bar_width = 0.59999999999999998
        bloom_intensity = 0.5
        fade_when_idle = true
        inner_diameter = 0.69999999999999996
        primary_color = "primary"
        ring_opacity = 0.80000000000000004
        rotation_speed = 0.5
        secondary_color = "secondary"
        sensitivity = 1.5
        visualization_mode = "bars_rings"
        wave_thickness = 1.0

[nightlight]
enabled = true

[shell]
avatar_path = "/home/dominictdavies/MyNixOS/assets/profile.png"
telemetry_enabled = true

    [shell.panel]
    control_center_position = "center"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screenshot]
    directory = "/home/dominictdavies/Pictures/Screenshots"

    [shell.shadow]
    direction = "center"

[theme]
source = "wallpaper"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kitty", "niri", "starship" ]

[wallpaper]
directory = "/home/dominictdavies/MyNixOS/assets/wallpapers"

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/dominictdavies/MyNixOS/assets/wallpapers/stanley_parable_skip_button.png"

    [wallpaper.last]
    path = "/home/dominictdavies/MyNixOS/assets/wallpapers/stanley_parable_skip_button.png"

    [wallpaper.monitors.DP-2]
    path = "/home/dominictdavies/MyNixOS/assets/wallpapers/stanley_parable_desk.png"

    [wallpaper.monitors.DP-3]
    path = "/home/dominictdavies/MyNixOS/assets/wallpapers/stanley_parable_skip_button.png"

    [wallpaper.monitors.DP-4]
    path = "/home/dominictdavies/MyNixOS/assets/wallpapers/stanley_parable_desk_lined.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/dominictdavies/MyNixOS/assets/wallpapers/stanley_parable_desk.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/dominictdavies/MyNixOS/assets/wallpapers/stanley_parable_skip_button.png"

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

[widget.clock]
format = "{:%H:%M %d/%m}"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.volume]
show_label = false
