{ self, ... }:
{
  flake.nixosModules.dominatorHardware =
    # This file was generated by `nixos-generate-config`
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
        self.nixosModules.nvidia
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-c815ffaf-184c-4b0e-8e67-5a1d9adc5c62";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-c815ffaf-184c-4b0e-8e67-5a1d9adc5c62".device =
        "/dev/disk/by-uuid/c815ffaf-184c-4b0e-8e67-5a1d9adc5c62";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/0866-205D";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [ ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
