{ self, ... }:
{
  flake.nixosModules.dominoHardware =
    # This file was generated by `nixos-generate-config`
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
        self.nixosModules.framework
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "thunderbolt"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-e18aaae2-965e-4f3c-bd73-116a95dde50a";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-e18aaae2-965e-4f3c-bd73-116a95dde50a".device = "/dev/disk/by-uuid/e18aaae2-965e-4f3c-bd73-116a95dde50a";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/6397-47BC";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [ ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
